Components
BroederToon/Project5.2-Zweeloo pull request #10
Opened 2022-12-23 07:40 UTC by Yannieck

2022-12-23 08:49 UTC, FrancaBaars requested changes

2022-12-23 08:49 UTC, FrancaBaars commented on mobile/function/map_page_function.js
> +                    onPress={() => onMarkerClick(data.poi[i].name, data.poi[i].id)}
Waarom stuur je hier de naam ook mee?

2022-12-23 08:49 UTC, FrancaBaars commented on mobile/function/map_page_function.js
>  import { useCallback, useEffect, useState } from "react";
Ongebruikte import weghalen hier

2022-12-23 08:49 UTC, FrancaBaars commented on mobile/function/map_page_function.js
> +        nav.navigate("PointOfInterestInfoPage", { name: name, poiId: id });
Hier ook, waarom stuur je hier de naam mee?

2022-12-23 08:49 UTC, FrancaBaars commented on mobile/screens/map_page.js
>  import { MaterialIcons } from "@expo/vector-icons";
Op regel 1 ongebruikte import

2022-12-23 08:49 UTC, FrancaBaars commented on mobile/function/poi_info_page_functions.js
>      //return all the information of the poi that has been clicked
Aan het begin ongebruikte imports weghalen

2022-12-23 08:49 UTC, FrancaBaars commented on mobile/screens/route_list.js
>  import { Text, View, Image, ScrollView, Pressable } from "react-native";
ongebruikte imports

2022-12-23 08:49 UTC, FrancaBaars commented on mobile/screens/route_list.js
>  /**
Comments voor pagina's moeten denk ik overal op deze manier denk ik

2022-12-23 08:49 UTC, FrancaBaars commented on mobile/screens/route_type_page.js
>  import { styles } from "../styles/basic_styles";
Ongebruikte import op regel 1

2022-12-23 08:49 UTC, FrancaBaars commented on mobile/screens/see_route_page.js
> +                                name: navigate.route.params.name,
Hier ook, waarom wordt hier de naam meegestuurd?

2022-12-23 08:49 UTC, FrancaBaars commented on mobile/styles/line_styles.js
> +
Comments graag

2022-12-23 08:49 UTC, FrancaBaars commented on mobile/styles/sponsor_styles.js
>      // Each sponsor tile
Ook in de css zijn de comments niet overal hetzelfde

2022-12-23 08:49 UTC, FrancaBaars commented on mobile/styles/line_styles.js
> +        marginBottom: 25,
Ik denk dat deze margin te groot is. want er is een te grote ruimte tussen de header en de route overzicht. Maar kan ook zijn dat er ergens anders een margin te groot is.

2022-12-23 08:49 UTC, FrancaBaars commented on mobile/components/header.js
> +    const nav = useNavigation();
Er moet op de header een max -width op dit moment valt de terug pijl buiten het scherm als de titel te lang is.

2022-12-23 09:44 UTC, elementer23 requested changes

2022-12-23 09:44 UTC, elementer23 commented on mobile/components/header.js
> +                </Text>
Voor een oplossing van een te lange titel, zou je de titel een width kunnen geven dat die onder elkaar valt bij een bepaalde lengte.

2023-01-02 08:53 UTC, elementer23 approved these changes

2023-01-02 08:53 UTC, elementer23 commented on mobile/function/map_page_function.js
> +        console.log(json);
ook console.log weg halen tenzij je die gebruikt die er met een reden is natuurlijk

2023-01-02 08:53 UTC, elementer23 commented on mobile/function/get_sponsors.js
> +    console.log("Loading sponsor data");
ook console.log weg halen tenzij je die gebruikt die er met een reden is natuurlijk

2023-01-02 08:53 UTC, elementer23 commented on mobile/function/poi_info_page_functions.js
> +        console.log(json);
ook console.log weg halen tenzij je die gebruikt die er met een reden is natuurlijk

2023-01-02 08:53 UTC, elementer23 commented on mobile/function/route_list_functions.js
> +        console.log(json);
ook console.log weg halen tenzij je die gebruikt die er met een reden is natuurlijk

2023-01-02 08:53 UTC, elementer23 commented on mobile/function/route_list_functions.js
> +    console.log("Loading routes");
ook console.log weg halen tenzij je die gebruikt die er met een reden is natuurlijk

2023-01-02 09:35 UTC, BroederToon approved these changes

2023-01-02 13:11 UTC, FrancaBaars approved these changes

2023-01-02 13:14 UTC, merged