commented some code, for if the change doesn't work
BroederToon/Project5.2-Zweeloo pull request #11
Opened 2023-01-02 14:41 UTC by elementer23

got rid of all the usecallback functions, and do not delete the commented code until everything is 100% correct with the function

2023-01-02 15:13 UTC, FrancaBaars requested changes
De uitgecommente code graag weghalen en de ongebruikte import graag weghalen

2023-01-03 09:33 UTC, Yannieck approved these changes

2023-01-03 09:47 UTC, Yannieck commented
👍

2023-01-03 09:48 UTC, FrancaBaars approved these changes

2023-01-03 09:48 UTC, merged