InfoPage
BroederToon/Project5.2-Zweeloo pull request #12
Opened 2023-01-03 09:57 UTC by Yannieck

2023-01-03 10:11 UTC, FrancaBaars requested changes
Werkt goed alleen paar dingen veranderen
Graag namen van de bestanden veranderen

2023-01-03 10:11 UTC, FrancaBaars commented on mobile/function/get_sponsors.js
> +                                }
Willen we hier een console.error of iets wat de gebruiker kan zien?

2023-01-03 10:11 UTC, FrancaBaars commented on mobile/screens/aboutOgranisation.js
> +
Ongebruikte import weghalen graag

2023-01-03 10:11 UTC, FrancaBaars commented on mobile/screens/aboutApp.js
> +
Ongebruikte import weghalen graag

2023-01-03 10:11 UTC, FrancaBaars commented on mobile/screens/information_page.js
> +                    style={{
Style graag in apart bestand staat in de code conventies dacht ik

2023-01-03 10:38 UTC, elementer23 approved these changes

2023-01-03 12:05 UTC, FrancaBaars requested changes
De naamgeving van de files is nog niet veranderd

2023-01-04 14:01 UTC, FrancaBaars approved these changes

2023-01-04 14:02 UTC, merged