setting up development environment and conventions
BroederToon/Project5.2-Zweeloo pull request #2
Opened 2022-11-05 20:56 UTC by BroederToon

toegevoegd:
een environment voor de react native based applicatie.
een conventions file met daarin een aantal afspraken.
een README

2022-11-06 10:00 UTC, FrancaBaars commented on CONVENTIONS.MD
> +geen memes in #general\
Welke #general?

2022-11-06 10:00 UTC, FrancaBaars commented on CONVENTIONS.MD
> +folder namen beginnen met een kleine letter\
Wil je folder namen dan helemaal in kleine letters, wat als er meerdere woorden zijn?

2022-11-06 10:00 UTC, FrancaBaars commented on CONVENTIONS.MD
> +statements eindigen met ;\
Hier staat de \ ook in de tekst, even weghalen

2022-11-06 11:22 UTC, FrancaBaars reviewed
Paar kleine dingen dan is het goed

2022-11-06 11:22 UTC, FrancaBaars commented on CONVENTIONS.MD
> +- lower case met een "-" ertussen\
De \ staat nu ook in de tekst. Er staan er nog een paar in dit bestand, even weg halen

2022-11-06 11:22 UTC, FrancaBaars commented on CONVENTIONS.MD
> +- package namen worden in lowercase geschreven en zo kort mogelijk. alleen wanneer de leesbaarheid er anders onder lijdt, kan de naam opgedeeld worden met punten
Hier bedoel je volgens mij folders niet packages

2022-11-07 08:39 UTC, FrancaBaars commented on CONVENTIONS.MD
> +- commits worden in het nederlands geschreven
Dit graag in het Engels

2022-11-07 08:47 UTC, FrancaBaars commented on CONVENTIONS.MD
> +- commits worden in het nederlands geschreven
Dit graag in het Engels

2022-11-25 07:57 UTC, FrancaBaars commented on CONVENTIONS.MD
> +- .js files zijn in PascalCase
Dit moet veranderd worden volgens Yannieck:
snake_case altijd

2022-11-29 10:00 UTC, FrancaBaars requested changes

2022-11-29 10:00 UTC, FrancaBaars commented on mobile/screens/Home.js
> +  StyleSheet,
Graag alle niet gebruikte import eruit halen op alle pagina's graag

2022-11-29 10:00 UTC, FrancaBaars commented on mobile/screens/Home.js
> +const Home = () => {
We zouden alles classe based doen, dit ook graag aanpassen. op alle pagina's

2022-11-29 10:00 UTC, FrancaBaars commented on mobile/App.js
> +export const BaseNavigator = () => (
Als deze kan worden omgezet naar een classe graag doen, als dat niet kan even met ons bespreken

2022-12-01 10:26 UTC, FrancaBaars requested changes
Graag de bestandsnamen veranderen

2022-12-01 10:26 UTC, FrancaBaars commented on CONVENTIONS.MD
> +-   commits worden in het nederlands geschreven
dit graag engels

2022-12-01 12:41 UTC, FrancaBaars approved these changes
Ziet er goed uit

2022-12-01 12:42 UTC, Yannieck approved these changes

2022-12-01 12:43 UTC, merged