Card list
BroederToon/Project5.2-Zweeloo pull request #3
Opened 2022-12-06 13:49 UTC by elementer23

2022-12-08 09:02 UTC, FrancaBaars requested changes
Paar kleine dingen aanpassen dan vind ik hem prima

2022-12-08 09:02 UTC, FrancaBaars commented on mobile/function/route_list_functions.js
> +/**
Ik zou hier per kleine functie uitleggen wat de functie doet en niet een grote lap tekst zoals het er nu staat.

2022-12-08 09:02 UTC, FrancaBaars commented on mobile/function/route_list_functions.js
> +        const response = await fetch("http://10.232.0.114:3000/api/routes/all");
Op dit moment haal je alle routes op en niet alleen de wandel routes. Ik weet niet of dit klopt

2022-12-08 09:02 UTC, FrancaBaars commented on mobile/function/route_list_functions.js
> +        if (!json.length >= 0) {
if statement doet hier niks dus deze kan weg

2022-12-13 14:41 UTC, FrancaBaars requested changes
Paar kleine dingen en dan is het goed

2022-12-13 14:41 UTC, FrancaBaars commented on mobile/function/route_list_functions.js
> +                                        <Text>ZIE ROUTE</Text>
Hier moet een nav.navigate komen, maar ik weet niet of we die er nu al in willen zetten, of pas als die pagina bestaat.

2022-12-13 14:41 UTC, FrancaBaars commented on mobile/screens/route_type_page.js
> +import { Text, View, Button, Pressable } from "react-native";
Button wordt hier niet gebruikt

2022-12-13 14:41 UTC, FrancaBaars commented on mobile/screens/route_list.js
> +                                    color="red"
Graag de rood maken van het huisstijldocument

2022-12-13 14:41 UTC, FrancaBaars commented on mobile/styles/basic_styles.js
>  export const styles = StyleSheet.create({
Graag de kleur van het lettertype de kleur maken van het huisstijldocument.

2022-12-13 15:11 UTC, FrancaBaars approved these changes

2022-12-13 15:28 UTC, BroederToon commented on mobile/function/route_list_functions.js
> +import { Feather } from "@expo/vector-icons";
kunnen deze "@expo/vector-icons" imports niet op 1 lijn?

2022-12-13 15:28 UTC, BroederToon commented on mobile/function/route_list_functions.js
> +    } else {
ik zou de else er uit halen. een else na een return is zinloze indenting imo

2022-12-13 15:28 UTC, BroederToon commented on mobile/function/route_list_functions.js
> +        } else {
zie comment hierboven

2022-12-13 15:36 UTC, BroederToon approved these changes

2022-12-13 15:37 UTC, merged