Styling route type page
BroederToon/Project5.2-Zweeloo pull request #6
Opened 2022-12-19 12:51 UTC by FrancaBaars

2022-12-19 21:17 UTC, Yannieck requested changes
Verder helemaal prima 👍👍

2022-12-19 21:17 UTC, Yannieck commented on mobile/screens/route_type_page.js
> +import { Ionicons } from "@expo/vector-icons";
Deze kunnen gecombineerd worden regel 5 en 6

2022-12-19 21:17 UTC, Yannieck commented on mobile/screens/route_type_page.js
> +                                size={100}
Misschien deze iets kleiner maken, want de wandelaar is op het moment een stuk groter dan de fietser, hoeft niet perse maar staat wel beter imo

2022-12-20 09:18 UTC, elementer23 requested changes

2022-12-20 09:18 UTC, elementer23 commented on mobile/styles/route-type-style.js
> +        fontWeight: "bold",
Like usual je vergeet gewoon weer commentaar aan de styling toe te voegen

2022-12-20 10:17 UTC, elementer23 approved these changes

2022-12-20 10:17 UTC, Yannieck approved these changes

2022-12-20 10:18 UTC, merged