Poi info
BroederToon/Project5.2-Zweeloo pull request #8
Opened 2022-12-20 12:27 UTC by elementer23

2022-12-20 12:57 UTC, FrancaBaars requested changes

2022-12-20 12:57 UTC, FrancaBaars commented on mobile/.env
> +IP = http://10.232.7.233:3000
Deze hoort in de gitignore te staan, dit moet dus gefixt worden

2022-12-20 12:57 UTC, FrancaBaars commented on mobile/function/map_page_function.js
> +        console.log("we komen bij de fetchdata");
Deze console.logs moeten er of uit of verandertworden naar een zin, die logisch is.

2022-12-20 12:57 UTC, FrancaBaars commented on mobile/function/map_page_function.js
>          console.log(id);
Hier ook de console.log

2022-12-20 12:57 UTC, FrancaBaars commented on mobile/screens/Point_of_interest_info_page.js
> +import { styles } from "../styles/basic_styles";
Naam van het bestand moet met een kleine letter

2022-12-20 12:57 UTC, FrancaBaars commented on mobile/function/point_of_interest_info_page_functions.js
> +                />
Het icoontje komt nu nog wel eens in de knoop met de titel

2022-12-20 12:57 UTC, FrancaBaars commented on mobile/screens/Point_of_interest_info_page.js
> +const Point_of_interest_info_page = (navigate) => {
Hier moeten volgens mij geen - tussen de naam

2022-12-20 13:06 UTC, Yannieck commented on mobile/function/point_of_interest_info_page_functions.js
> +        return loadScreen();
Je kan deze laad functie ook veranderen naar een ActivityIndicator als je wilt

2022-12-20 13:11 UTC, Yannieck requested changes

2022-12-20 13:11 UTC, Yannieck commented on mobile/function/point_of_interest_info_page_functions.js
> + *
Beschrijving van functie ontbreekt

2022-12-20 13:11 UTC, Yannieck commented on mobile/screens/Point_of_interest_info_page.js
> +const Point_of_interest_info_page = (navigate) => {
Misschien gewoon hernoemen naar PoiInfoPage

2022-12-20 13:11 UTC, Yannieck commented on mobile/App.js
> +            component={Point_of_interest_info_page}
Geen lage streepjes in PascalCase

2022-12-21 08:38 UTC, FrancaBaars requested changes
1 klein dingetje nog en dan vind ik hem goed

2022-12-21 08:38 UTC, FrancaBaars commented on mobile/screens/Point_of_interest_info_page.js
> +import { styles } from "../styles/basic_styles";
Dit bestand is bij mij nog steeds met een hoofdletter dus geeft hij een error in de app.js

2022-12-21 10:07 UTC, FrancaBaars approved these changes

2022-12-21 10:13 UTC, Yannieck approved these changes

2022-12-21 10:13 UTC, merged